// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandevuSistemi.Models.AdminSiniflar;

#nullable disable

namespace RandevuSistemi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250614134915_Migbarber")]
    partial class Migbarber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoundedYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.AdminLogin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AdminLogin");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Barber", b =>
                {
                    b.Property<int>("BarberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarberId"));

                    b.Property<string>("BarberDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expertise")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarberId");

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Campaigns", b =>
                {
                    b.Property<int>("CampaignsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignsId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampaignsId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Comments", b =>
                {
                    b.Property<int>("CommentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentsID"));

                    b.Property<string>("COmmentsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentsID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.CustomerComment", b =>
                {
                    b.Property<int>("CustomerCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerCommentID"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerCommentID");

                    b.HasIndex("BarberId");

                    b.ToTable("CustomerComments");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Hairdresser", b =>
                {
                    b.Property<int>("HairdresserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HairdresserID"));

                    b.Property<int>("BarberID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HairdresserID");

                    b.HasIndex("BarberID");

                    b.ToTable("Hairdressers");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.HomePage", b =>
                {
                    b.Property<int>("HomePageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomePageID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HomePageID");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Messages", b =>
                {
                    b.Property<int>("MessagesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessagesID"));

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessagesID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.MyReservations", b =>
                {
                    b.Property<int>("MyReservationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MyReservationsID"));

                    b.Property<string>("Barber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MyReservationsID");

                    b.ToTable("MyReservations");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Price", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDate", b =>
                {
                    b.Property<int>("ReservationDateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationDateID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("ReservationHourId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("ReservationDateID");

                    b.HasIndex("ReservationHourId");

                    b.ToTable("ReservationsDate");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDays", b =>
                {
                    b.Property<int>("ReservationDaysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationDaysID"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationDaysID");

                    b.HasIndex("BarberId");

                    b.ToTable("ReservationsDays");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationHours", b =>
                {
                    b.Property<int>("ReservationHoursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationHoursID"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("ReservationDaysID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("ReservationHoursID");

                    b.HasIndex("ReservationDaysID");

                    b.ToTable("ReservationHours");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Reserved", b =>
                {
                    b.Property<int>("ReservedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservedID"));

                    b.Property<int>("BarberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReservationDateID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationDaysID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationHoursID")
                        .HasColumnType("int");

                    b.Property<string>("Situation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.HasKey("ReservedID");

                    b.HasIndex("BarberID");

                    b.HasIndex("ReservationDateID");

                    b.HasIndex("ReservationDaysID");

                    b.HasIndex("ReservationHoursID");

                    b.ToTable("Reserveds");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Services", b =>
                {
                    b.Property<int>("ServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicesID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicesID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.SocialMedia", b =>
                {
                    b.Property<int>("SocialMediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialMediaID"));

                    b.Property<string>("SocialLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaID");

                    b.ToTable("SocialMedias");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.CustomerComment", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.Barber", "Barber")
                        .WithMany("CustomerComments")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Hairdresser", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.Barber", "Barber")
                        .WithMany("Hairdresser")
                        .HasForeignKey("BarberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Price", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.Category", "Category")
                        .WithMany("Price")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDate", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.ReservationHours", "ReservationHour")
                        .WithMany("ReservationDate")
                        .HasForeignKey("ReservationHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationHour");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDays", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.Barber", "Barber")
                        .WithMany("ReservationDays")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationHours", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.ReservationDays", "ReservationDays")
                        .WithMany("ReservationHours")
                        .HasForeignKey("ReservationDaysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationDays");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Reserved", b =>
                {
                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.Barber", "Barber")
                        .WithMany("Reserveds")
                        .HasForeignKey("BarberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.ReservationDate", "ReservationDates")
                        .WithMany("Reserveds")
                        .HasForeignKey("ReservationDateID");

                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.ReservationDays", "ReservationDays")
                        .WithMany("Reserveds")
                        .HasForeignKey("ReservationDaysID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RandevuSistemi.Models.AdminSiniflar.ReservationHours", "ReservationHours")
                        .WithMany("Reserveds")
                        .HasForeignKey("ReservationHoursID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("ReservationDates");

                    b.Navigation("ReservationDays");

                    b.Navigation("ReservationHours");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Barber", b =>
                {
                    b.Navigation("CustomerComments");

                    b.Navigation("Hairdresser");

                    b.Navigation("ReservationDays");

                    b.Navigation("Reserveds");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.Category", b =>
                {
                    b.Navigation("Price");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDate", b =>
                {
                    b.Navigation("Reserveds");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationDays", b =>
                {
                    b.Navigation("ReservationHours");

                    b.Navigation("Reserveds");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AdminSiniflar.ReservationHours", b =>
                {
                    b.Navigation("ReservationDate");

                    b.Navigation("Reserveds");
                });
#pragma warning restore 612, 618
        }
    }
}
